Repository angular/dev-infra, pull requests merged in 2021-08, with the labels that each got.

#125 fix: properly handle empty stdout responses for buildifier checks
  ng-dev/format/formatters/buildifier.ts
Labels: cla: yes, action: merge

#126 fix(ng-dev): publishing fails if pre-release is cut for new minor/major
  WORKSPACE
  ng-dev/commit-message/parse.ts
  ng-dev/release/notes/cli.ts
  ng-dev/release/notes/commits/get-commits-in-range.png
  ng-dev/release/notes/commits/get-commits-in-range.ts
  ng-dev/release/notes/commits/unique-commit-id.ts
  ng-dev/release/notes/release-notes.ts
  ng-dev/release/publish/actions.ts
  ng-dev/release/publish/actions/branch-off-next-branch.ts
  ng-dev/release/publish/actions/cut-lts-patch.ts
  ng-dev/release/publish/actions/cut-new-patch.ts
  ng-dev/release/publish/actions/cut-next-prerelease.ts
  ng-dev/release/publish/actions/cut-release-candidate-for-feature-freeze.ts
  ng-dev/release/publish/actions/cut-stable.ts
  ng-dev/release/publish/cli.ts
  ng-dev/release/publish/test/BUILD.bazel
  ng-dev/release/publish/test/branch-off-next-branch-testing.ts
  ng-dev/release/publish/test/common.spec.ts
  ng-dev/release/publish/test/configure-next-as-major.spec.ts
  ng-dev/release/publish/test/cut-lts-patch.spec.ts
  ng-dev/release/publish/test/cut-new-patch.spec.ts
  ng-dev/release/publish/test/cut-next-prerelease.spec.ts
  ng-dev/release/publish/test/cut-release-candidate-for-feature-freeze.spec.ts
  ng-dev/release/publish/test/cut-stable.spec.ts
  ng-dev/release/publish/test/move-next-into-feature-freeze.spec.ts
  ng-dev/release/publish/test/move-next-into-release-candidate.spec.ts
  ng-dev/release/publish/test/release-notes/release-notes-utils.ts
  ng-dev/release/publish/test/tag-recent-major-as-latest.spec.ts
  ng-dev/release/publish/test/test-utils.ts
  ng-dev/release/publish/test/test-utils/action-mocks.ts
  ng-dev/release/publish/test/test-utils/github-api-testing.ts
  ng-dev/release/publish/test/test-utils/sandbox-git-client.ts
  ng-dev/release/publish/test/test-utils/sandbox-testing.ts
  ng-dev/release/publish/test/test-utils/staging-test.ts
  ng-dev/release/publish/test/test-utils/test-action.ts
  ng-dev/release/publish/test/test-utils/test-utils.ts
  ng-dev/release/versioning/next-prerelease-version.ts
  ng-dev/release/versioning/version-tags.ts
  ng-dev/utils/git/git-client.ts
  ng-dev/utils/testing/dedent.ts
  ng-dev/utils/testing/virtual-git-client.ts
  tools/git-toolchain/BUILD.bazel
  tools/git-toolchain/alias.bzl
  tools/git-toolchain/toolchain.bzl
  tsconfig.json
Labels: cla: yes, action: review

#140 test(ng-dev): fix usage of TEST_TMPDIR
  ng-dev/release/publish/test/test-utils/action-mocks.ts
Labels: cla: yes, action: merge

#157 fix: remove husky install from `scripts` section of package json for published npm package
  BUILD.bazel
Labels: cla: yes, action: merge

#158 feat(ng-dev): remove breaking change label configuration from merge command
  github-actions/breaking-changes-label/BUILD.bazel
  github-actions/breaking-changes-label/bundle.js
  github-actions/breaking-changes-label/main.ts
  ng-dev/pr/merge/BUILD.bazel
  ng-dev/pr/merge/config.ts
  ng-dev/pr/merge/constants.ts
  ng-dev/pr/merge/failures.ts
  ng-dev/pr/merge/pull-request.ts
Labels: cla: yes, action: merge

#161 fix(ng-dev): release fails if release notes are too long
  ng-dev/release/notes/context.ts
  ng-dev/release/notes/release-notes.ts
  ng-dev/release/notes/templates/changelog.ts
  ng-dev/release/notes/templates/github-release.ts
  ng-dev/release/publish/actions.ts
  ng-dev/release/publish/constants.ts
  ng-dev/release/publish/test/common.spec.ts
  ng-dev/release/publish/test/test-utils/github-api-testing.ts
  ng-dev/utils/git/github-urls.ts
Labels: cla: yes

#163 fix: use angular-robot@google.com as email when setting user.email in tooling git configuration
  .circleci/config.yml
  ng-dev/release/publish/test/test-utils/sandbox-testing.ts
Labels: cla: yes, action: merge

#169 feat(ng-dev): support for custom grouping when generating release notes
  github-actions/breaking-changes-label/main.js
  github-actions/slash-commands/main.js
  ng-dev/commit-message/parse.spec.ts
  ng-dev/commit-message/parse.ts
  ng-dev/commit-message/test-util.ts
  ng-dev/commit-message/validate.ts
  ng-dev/release/config/BUILD.bazel
  ng-dev/release/config/index.ts
  ng-dev/release/notes/context.ts
  ng-dev/release/notes/release-notes.ts
  ng-dev/release/notes/templates/changelog.ts
  ng-dev/release/notes/templates/github-release.ts
  ng-dev/release/publish/test/cut-lts-patch.spec.ts
  ng-dev/release/publish/test/cut-new-patch.spec.ts
  ng-dev/release/publish/test/cut-next-prerelease.spec.ts
  ng-dev/release/publish/test/cut-release-candidate-for-feature-freeze.spec.ts
  ng-dev/release/publish/test/cut-stable.spec.ts
  ng-dev/release/publish/test/move-next-into-feature-freeze.spec.ts
  ng-dev/release/publish/test/move-next-into-release-candidate.spec.ts
  ng-dev/release/publish/test/release-notes/context.spec.ts
  ng-dev/release/publish/test/release-notes/generation.spec.ts
Labels: cla: yes, action: merge, action: review

#188 build: fix changelog action constructing incorrect version
  tools/local-actions/changelog/lib/main.ts
  tools/local-actions/changelog/main.js
Labels: cla: yes
