Repository angular/dev-infra, pull requests merged in 2021-11, with the labels that each got.

#282 fix(ng-dev/release): fix description for TagRecentMajorAsLatest action
  ng-dev/release/publish/actions/tag-recent-major-as-latest.ts
Labels: action: merge, action: review

#285 feat(bazel): allow integration commands to resolve executables through expansion
  bazel/integration/index.bzl
  bazel/integration/test_runner/main.ts
  bazel/integration/test_runner/runner.ts
  bazel/integration/tests/external_command_script/BUILD.bazel
  bazel/integration/tests/external_command_script/external_script.sh
Labels: action: merge

#294 revert abuse orb setup
  .circleci/config.yml
Labels: action: merge

#302 ci: set up OSS abuse orb to monitor usage on the angular/angular repo
  .circleci/config.yml
Labels: action: merge

#307 refactor: ship `BUILD.bazel` files for shared scripts
  package.bzl
  shared-scripts/BUILD.bazel
  shared-scripts/README.md
Labels: action: review
