Repository angular/dev-infra, pull requests merged in 2022-03, with the labels that each got.

#442 build: fix yarn install with vendored yarn due to bug in `rules_nodejs`
  .gitignore
  .yarn/yarn.js
  WORKSPACE
Labels: action: merge, action: review

#449 fix(ng-dev/release): only match on a single character prefixed version for snapshotting
  ng-dev/release/stamping/env-stamp.ts
Labels: action: merge

#451 feat(ng-dev): support skipping version stamp in release stamp env
  .bazelrc
  ng-dev/release/stamping/_private_main.ts
  ng-dev/release/stamping/cli.ts
  ng-dev/release/stamping/env-stamp.ts
Labels: action: merge

#450 refactor(ng-dev): expose git and github client classes in ng-dev entry-point
  ng-dev/index.ts
Labels: action: review

#458 build: enable node module symlinking for Bazel
  WORKSPACE
Labels: action: review

#456 refactor: no longer import `JSModuleInfo` provider through backwards-compat entry
  bazel/extract_js_module_output.bzl
  bazel/spec-bundling/spec-entrypoint.bzl
Labels: action: review

#463 build: update jasmine to ~4.0
  package.json
  yarn.lock
Labels: dependencies, action: merge, comp: build

#464 fix(ng-dev): correctly indent bullets in breaking changes and deprecations sections
  ng-dev/release/notes/context.ts
  ng-dev/release/publish/test/release-notes/generation.spec.ts
  tools/local-actions/changelog/main.js
Labels: domain: release automation, action: merge

#475 fix(bazel): use correct `LinkerPackageMappingInfo` field name
  bazel/extract_js_module_output.bzl
Labels: action: review

#493 feat(bazel/api-golden): allow for module types to be provided
  bazel/api-golden/BUILD.bazel
  bazel/api-golden/index.bzl
  bazel/api-golden/index.ts
  bazel/api-golden/index_npm_packages.ts
  bazel/api-golden/module_mappings.ts
  bazel/api-golden/test/BUILD.bazel
  bazel/api-golden/test/fixtures/test_package/testing/namespace-alias.ts
  bazel/api-golden/test/fixtures/test_package/testing/nested.d.ts
  bazel/api-golden/test/goldens/test_package/testing/nested/index.md
  bazel/api-golden/test_api_report.ts
  package.json
  yarn.lock
Labels: action: review

#494 fix(ng-dev): fix github token retrieval logic
  ng-dev/utils/git/github-yargs.ts
Labels: domain: caretaking
