Repository angular/dev-infra, pull requests merged in 2022-02, with the labels that each got.

#378 build: fix scorecard config
  .github/workflows/scorecard.yml
Labels: action: merge

#386 refactor: allow http-server to serve dotfiles
  bazel/http-server/server.ts
Labels: action: merge, action: cleanup

#403 feat(bazel): setup karma web test wrapper with "local" debug target
  bazel/BUILD.bazel
  bazel/karma/BUILD.bazel
  bazel/karma/index.bzl
  bazel/karma/karma-debug-config.js
Labels: action: review

#416 fix(ng-dev): uncommitted changes check returning false-positives
  github-actions/commit-message-based-labels/main.js
  github-actions/slash-commands/main.js
  ng-dev/utils/git/git-client.ts
  tools/local-actions/changelog/main.js
Labels: action: review

#422 build: move `@angular/compiler-cli` to `devDependencies`
  package.json
Labels: action: review
