Repository angular/dev-infra, pull requests merged in 2022-06, with the labels that each got.

#594 refactor(ng-dev): do not print `undefined` when release prechecks fail
  ng-dev/release/publish/external-commands.ts
Labels: action: merge

#648 feat(circleci-orb): create orb command for rebasing pull requests on the target branch
  circleci-orb/commands/rebase-on-target-branch.yml
  circleci-orb/scripts/rebase-on-target-branch/index.ts
Labels: action: merge, action: review

#656 refactor(ng-dev): remove unused `matchesPattern` utility
  ng-dev/pr/common/validation/validations.ts
  ng-dev/pr/config/index.ts
  ng-dev/pr/merge/pull-request.ts
  ng-dev/pr/merge/strategies/api-merge.ts
Labels: action: merge

#665 refactor(ng-dev): do not capture Angular robot in release notes
  ng-dev/release/notes/context.ts
Labels: action: review

#662 feat(bazel): move js mapping size tracking tool to dev-infra
  .ng-dev/commit-message.mts
  .prettierignore
  bazel/BUILD.bazel
  bazel/map-size-tracking/BUILD.bazel
  bazel/map-size-tracking/file_size_compare.ts
  bazel/map-size-tracking/file_size_data.ts
  bazel/map-size-tracking/index.bzl
  bazel/map-size-tracking/index.ts
  bazel/map-size-tracking/size_tracker.ts
  bazel/map-size-tracking/test/BUILD.bazel
  bazel/map-size-tracking/test/file_size_compare_spec.ts
  bazel/map-size-tracking/test/file_size_data_spec.ts
  bazel/map-size-tracking/test/fixture-app/BUILD.bazel
  bazel/map-size-tracking/test/fixture-app/main.ts
  bazel/map-size-tracking/test/fixture-app/package.json
  bazel/map-size-tracking/test/fixture-app/test-component.ts
  bazel/map-size-tracking/test/size-golden.json
  bazel/map-size-tracking/test/size_tracking_spec.ts
  package.json
  yarn.lock
Labels: action: review

#666 build: enable self-hosted runner for angular/ngcc-validation
  .github/ng-renovate/runner-config.js
Labels: action: merge

#668 feat(github-actions): create org-file-sync action
  .prettierignore
  github-actions/org-file-sync/BUILD.bazel
  github-actions/org-file-sync/README.md
  github-actions/org-file-sync/action.yml
  github-actions/org-file-sync/main.js
  github-actions/org-file-sync/src/main.ts
Labels: action: merge, action: review

#672 fix(github-actions): add logging and set undefined for `repoSha` and `repoFileContent`
  github-actions/org-file-sync/main.js
  github-actions/org-file-sync/src/main.ts
Labels: action: merge

#674 fix(github-actions): actually log the repos and files being synced
  github-actions/org-file-sync/main.js
  github-actions/org-file-sync/src/main.ts
Labels: action: merge
