Repository angular/dev-infra, pull requests merged in 2023-01, with the labels that each got.

#963 build: fix scorecard action failing
  .github/workflows/scorecard.yml
Labels: area: build & ci

#964 build: fix scorecard signing by ensuring permissions are only set for job
  .github/workflows/scorecard.yml
Labels: area: build & ci

#966 build: change snapshot build token variable to `SNAPSHOT_BUILDS_GITHUB_TOKEN`
  .circleci/publish_to_github.sh
Labels: area: build & ci

#971 feat(bazel): never build metafile by default in esbuild actions
  bazel/esbuild/index.bzl
Labels: detected: feature

#973 fix(github-actions): close superseded PRs when using create-pr-for-changes
  github-actions/create-pr-for-changes/lib/main.ts
  github-actions/create-pr-for-changes/main.js
Labels: action: merge, target: patch, area: build & ci

#974 build: fix ng-renovate lock file after renovate
  .github/ng-renovate/yarn.lock
Labels: area: build & ci

#979 feat(ng-dev): allow for additional custom stamping
  ng-dev/BUILD.bazel
  ng-dev/index.ts
  ng-dev/release/stamping/_private_main.ts
  ng-dev/release/stamping/cli.ts
  ng-dev/release/stamping/env-stamp.ts
Labels: detected: feature

#981 feat(ng-dev): expose `convertVersionBranchToSemVer` function
  .github/local-actions/branch-manager/main.js
  ng-dev/release/versioning/version-branches.ts
Labels: detected: feature

#984 ci: run renovate every 60 instead of 30 minutes
  .github/workflows/ng-renovate.yml
Labels: action: merge, area: build & ci

#985 ci: disable renovate for ngcc-validation repository
  .github/ng-renovate/runner-config.js
Labels: action: merge

#983 ci: enable renovate cache
  .github/ng-renovate/runner-config.js
  .github/workflows/ng-renovate.yml
Labels: action: merge, area: build & ci

#986 ci: set up `GITHUB_COM_TOKEN` in renovate config
  .github/workflows/ng-renovate.yml
Labels: action: merge, area: build & ci

#987 ci: limit concurrent requests to `api.github.com`
  .github/ng-renovate/runner-config.js
Labels: action: merge, area: build & ci

#992 fix(github-actions): do Github requests serially in branch manager
  github-actions/branch-manager/lib/main.ts
  github-actions/branch-manager/main.js
Labels: action: review, target: patch
