Repository angular/dev-infra, pull requests merged in 2023-09, with the labels that each got.

#1363 docs: remove duplicate import
  bazel/browsers/update-script/firefox.ts
Labels: action: merge, area: docs

#1383 fix(dev-infra): update `zone.js` import to use modern
  bazel/benchmark/component_benchmark/defaults/index.ts
Labels: action: review

#1381 feat(api-gen): create skeleton for api doc extraction
  .ng-dev/commit-message.mts
  api-gen/extraction/BUILD.bazel
  api-gen/extraction/extract_api_to_json.bzl
  api-gen/extraction/index.ts
  api-gen/extraction/test/BUILD.bazel
  api-gen/extraction/test/fake-source.ts
  api-gen/rendering/BUILD.bazel
  api-gen/rendering/entities.ts
  api-gen/rendering/index.ts
  api-gen/rendering/processing.ts
  api-gen/rendering/render-entities.ts
  api-gen/rendering/render_api_to_html.bzl
  api-gen/rendering/rendering.ts
  api-gen/rendering/templates/component-reference.njk
  api-gen/rendering/test/BUILD.bazel
  api-gen/rendering/test/fake-entries.json
  package.json
  yarn.lock
Labels: detected: feature

#1387 feat(api-gen): add more structure to the transform pipeline
  api-gen/rendering/entities.ts
  api-gen/rendering/entities/categorization.ts
  api-gen/rendering/entities/entry_template_map.ts
  api-gen/rendering/entities/renderables.ts
  api-gen/rendering/entities/traits.ts
  api-gen/rendering/index.ts
  api-gen/rendering/nunjucks_loader.ts
  api-gen/rendering/processing.ts
  api-gen/rendering/render-entities.ts
  api-gen/rendering/rendering.ts
  api-gen/rendering/templates/class-member-list.njk
  api-gen/rendering/templates/class-member.njk
  api-gen/rendering/templates/class.njk
  api-gen/rendering/templates/component-reference.njk
  api-gen/rendering/test/fake-entries.json
  api-gen/rendering/transforms/class-transforms.ts
  api-gen/rendering/transforms/jsdoc-transforms.ts
  api-gen/rendering/transforms/member-transforms.ts
Labels: detected: feature

#1392 feat(api-gen): switch from nunjucks to tsx
  api-gen/rendering/BUILD.bazel
  api-gen/rendering/entities/categorization.ts
  api-gen/rendering/entities/entry_template_map.ts
  api-gen/rendering/index.ts
  api-gen/rendering/nunjucks_loader.ts
  api-gen/rendering/processing.ts
  api-gen/rendering/rendering.ts
  api-gen/rendering/templates/class-member-list.njk
  api-gen/rendering/templates/class-member-list.tsx
  api-gen/rendering/templates/class-member.njk
  api-gen/rendering/templates/class-member.tsx
  api-gen/rendering/templates/class-method-info.tsx
  api-gen/rendering/templates/class-reference.tsx
  api-gen/rendering/templates/class.njk
  api-gen/rendering/templates/parameter.tsx
  api-gen/rendering/templates/raw-html.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: detected: feature

#1397 feat(api-gen): add macro that combines api doc extraction and rendering
  api-gen/extraction/test/BUILD.bazel
  api-gen/generate_api_docs.bzl
  api-gen/test/BUILD.bazel
Labels: detected: feature

#1399 feat(api-gen): add api-gen to build-tools npm package
  api-gen/BUILD.bazel
  api-gen/extraction/BUILD.bazel
  api-gen/rendering/BUILD.bazel
  api-gen/test/BUILD.bazel
  bazel/BUILD.bazel
Labels: detected: feature

#1400 feat(api-gen): add module_name to the pipeline
  api-gen/extraction/extract_api_to_json.bzl
  api-gen/extraction/index.ts
  api-gen/extraction/test/BUILD.bazel
  api-gen/generate_api_docs.bzl
  api-gen/rendering/entities/categorization.ts
  api-gen/rendering/entities/renderables.ts
  api-gen/rendering/entities/traits.ts
  api-gen/rendering/index.ts
  api-gen/rendering/processing.ts
  api-gen/rendering/rendering.ts
  api-gen/rendering/test/fake-entries.json
  api-gen/rendering/transforms/class-transforms.ts
  api-gen/rendering/transforms/module-name.ts
  api-gen/test/BUILD.bazel
Labels: action: merge, detected: feature

#1402 feat(api-gen): call getApiDocumentation to produce real output
  api-gen/extraction/extract_api_to_json.bzl
  api-gen/extraction/index.ts
  api-gen/extraction/test/BUILD.bazel
  api-gen/extraction/test/fake-source.ts
  api-gen/generate_api_docs.bzl
  api-gen/test/BUILD.bazel
Labels: detected: feature
