Repository angular/dev-infra, pull requests merged in 2025-04, with the labels that each got.

#2697 feat(bazel): support Karma spec bundling with `rules_js`
  WORKSPACE
  bazel/karma/BUILD.bazel
  bazel/karma/index.bzl
  bazel/karma/karma-debug-config.cjs
  bazel/package.json
  bazel/pnpm-lock.yaml
  bazel/spec-bundling/index_rjs.bzl
Labels: detected: feature

#2710 feat(bazel): support more options in spec-bundle rule
  bazel/spec-bundling/index_rjs.bzl
Labels: action: review, detected: feature

#2714 build: speed up golden testing by parallelizing
  bazel/api-golden/BUILD.bazel
  bazel/api-golden/index_npm_packages.ts
  bazel/api-golden/test_api_report.ts
  bazel/package.json
  bazel/pnpm-lock.yaml
Labels: area: build & ci

#2724 feat(bazel): support `PORT` environment variable in http_server
  bazel/http-server/main.ts
Labels: detected: feature

#2728 fix(ng-dev): fix interactive rebase env
  ng-dev/pr/rebase/index.ts
Labels: action: merge

#2734 feat(bazel): update `http_server` to work with `rules_js`
  .bazelrc
  bazel/http-server/BUILD.bazel
  bazel/http-server/ibazel.mts
  bazel/http-server/index.bzl
  bazel/http-server/launcher_template.sh
  bazel/http-server/main.mts
  bazel/http-server/server.mts
  bazel/http-server/test/BUILD.bazel
  bazel/http-server/test/server-test.ts
  bazel/http-server/test/tsconfig.app.json
  bazel/package.json
  bazel/pnpm-lock.yaml
Labels: detected: feature
