Repository angular/dev-infra, pull requests merged in 2025-02, with the labels that each got.

#2586 fix(ng-dev): replace `bazel run @npm2//:sync` with `bazel sync --only=repo`
  ng-dev/release/publish/external-commands.ts
Labels: action: merge

#2588 build: remove windows testing and CI setup
  .github/workflows/ci.yml
Labels: area: build & ci

#2593 feat(github-actions): support specifying `shell` for configure RBE action
  github-actions/bazel/configure-remote/action.yml
  github-actions/bazel/configure-remote/configure-remote.cjs
  github-actions/bazel/configure-remote/index.ts
Labels: detected: feature

#2594 feat(github-actions): support RBE credentials in WSL
  github-actions/bazel/configure-remote/BUILD.bazel
  github-actions/bazel/configure-remote/configure-remote.cjs
  github-actions/bazel/configure-remote/index.ts
Labels: detected: feature

#2599 feat(github-actions): support RBE in windows action VMs
  github-actions/bazel/configure-remote/action.yml
  github-actions/bazel/configure-remote/configure-remote.cjs
  github-actions/bazel/configure-remote/index.ts
Labels: detected: feature

#2603 feat(github-actions): expose more common information in `setup-wsl` action
  github-actions/setup-wsl/action.yml
Labels: detected: feature

#2614 feat(github-actions): increase WSL memory
  github-actions/setup-wsl/action.yml
Labels: detected: feature

#2615 feat(github-actions): allow for WSL firewall interface to be configurable
  github-actions/setup-wsl/action.yml
Labels: detected: feature

#2616 feat(github-actions): support configuring networking mode for WSL action
  github-actions/setup-wsl/action.yml
Labels: detected: feature

#2617 feat(github-actions): add caching to WSL environment
  github-actions/setup-wsl/action.yml
Labels: detected: feature

#2622 feat(bazel): still support cross-compiling for Windows
  bazel/git-toolchain/BUILD.bazel
  bazel/remote-execution/BUILD.bazel
Labels: detected: feature
