Repository angular/dev-infra, pull requests merged in 2025-01, with the labels that each got.

#2539 fix(ng-dev): ensure release actions commit aspect lock files
  ng-dev/release/publish/actions.ts
  ng-dev/release/publish/actions/configure-next-as-major.ts
  ng-dev/release/publish/actions/exceptional-minor/prepare-exceptional-minor.ts
  ng-dev/release/publish/actions/shared/branch-off-next-branch.ts
Labels: action: review

#2541 feat(ng-dev): introduce an option to disable fixup commits in commit validation
  ng-dev/commit-message/validate.spec.ts
  ng-dev/commit-message/validate.ts
Labels: detected: feature

#2542 fix(ng-dev): move `disallowFixup` to commit message config
  ng-dev/commit-message/config.ts
  ng-dev/commit-message/validate.spec.ts
  ng-dev/commit-message/validate.ts
Labels: action: merge

#2557 feat(ng-dev): expose utilities for resolving yarn
  ng-dev/index.ts
Labels: detected: feature
