Repository angular/dev-infra, pull requests merged in 2025-05, with the labels that each got.

#2761 ci: update ng-renovate to use `ubuntu-latest`
  .github/workflows/ng-renovate.yml
Labels: action: merge, area: build & ci

#2764 ci: remove `angular/.github` for auto update
  .github/workflows/ng-renovate.yml
Labels: area: build & ci

#2773 fix(github-actions): delete obsolete branches and close superseded PRs
  github-actions/create-pr-for-changes/lib/main.ts
  github-actions/create-pr-for-changes/main.js
Labels: action: merge

#2772 feat(ng-dev): update `renovate.json` baseBranches when creating a new branch
  ng-dev/release/publish/actions/renovate-config-updates.ts
  ng-dev/release/publish/actions/shared/branch-off-next-branch.ts
Labels: action: review, detected: feature

#2777 ci: add comprehensive configuration for renovate dependency automation
  renovate-presets/default.json5
  renovate.json
Labels: action: merge, area: build & ci

#2784 ci: ignore `yarn` & `bazel` updates
  renovate-presets/default.json5
Labels: action: merge, area: build & ci

#2785 refactor: configure prettier to format json5
  ng-dev/format/formatters/prettier.ts
  renovate-presets/default.json5
Labels: action: merge, action: review

#2783 ci: bump renovate pnpm to `9.15.9`
  .github/workflows/ng-renovate.yml
Labels: action: merge, area: build & ci

#2782 build: create an `.npmrc`
  .npmrc
Labels: action: merge, area: build & ci

#2787 build: remove unused deps
  bazel/benchmark/driver-utilities/BUILD.bazel
  bazel/benchmark/driver-utilities/perf_util.ts
  package.json
  yarn.lock
Labels: action: merge, area: build & ci

#2788 fix(github-actions): explicitly allow renovate as a dependency through the license check
  github-actions/linting/licenses/dependency-review-config.yml
Labels: action: merge

#2789 ci: remove `yarn bazel sync --only=repo || true`
  renovate.json
Labels: action: merge

#2790 fix(github-actions): move `angular/**` to `matchPackageNames`
  renovate-presets/default.json5
Labels: action: merge

#2791 fix(github-actions): more `cross-repo angular dependencies` fixes
  renovate-presets/default.json5
Labels: action: merge

#2800 fix(github-action): replace `action: review` with `action: merge` in renovate preset
  renovate-presets/default.json5
Labels: action: review

#2805 refactor: delete `create-pr-for-changes` github action
  .prettierignore
  github-actions/create-pr-for-changes/BUILD.bazel
  github-actions/create-pr-for-changes/action.yml
  github-actions/create-pr-for-changes/lib/BUILD.bazel
  github-actions/create-pr-for-changes/lib/main.ts
  github-actions/create-pr-for-changes/main.js
  ng-dev/utils/BUILD.bazel
Labels: action: merge

#2809 ci: support for temporary branch-off of `build-tooling`
  .github/workflows/publish-snapshots.yml
Labels: area: build & ci

#2810 fix(ng-dev): ensure `update-generate-files` completes on error
  ng-dev/misc/generated-files/update-generated-files.ts
Labels: action: merge

#2816 ci: use `ubuntu-latest-4core` for Angular renovate
  .github/workflows/ng-renovate.yml
Labels: action: merge, area: build & ci

#2817 Revert "ci: use `ubuntu-latest-4core` for Angular renovate"
  .github/workflows/ng-renovate.yml
Labels: action: merge

#2823 ci: clean untracked files before running `postUpgradeTasks`
  renovate.json
Labels: area: build & ci

#2825 ci: reduce schedule for `google-closure-compiler`
  renovate-presets/default.json5
Labels: action: merge, area: build & ci

#2824 refactor(github-actions/commit-message-based-labels): prevent auto removal of already applied labels
  github-actions/commit-message-based-labels/lib/main.ts
  github-actions/commit-message-based-labels/main.js
Labels: action: review

#2828 Revert "ci: clean untracked files before running `postUpgradeTasks`"
  renovate.json
Labels: action: merge

#2831 build: update node.js toolchain to use `20.19.0`
  WORKSPACE
  tools/bazel-patches/build_bazel_rules_nodejs.patch
Labels: action: merge, area: build & ci
